/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Burbuja;
import Clases.Quicksort;
import Clases.Radix_Sort;
import Clases.Shell_Sort;
import java.awt.Color;

import java.awt.event.KeyEvent;
import static java.lang.System.console;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author HiYeaismin 8a
 */
public class Metodos_de_Ordenamiento extends javax.swing.JFrame {
    
    /**
     * Creates new form Metodos_de_Ordenamiento
     */
    public Metodos_de_Ordenamiento() {
        initComponents();
        setLocationRelativeTo(null);
             this.getContentPane().setBackground(Color.CYAN);
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        txtArreglo = new javax.swing.JTextField();
        lblArreglo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        numerosAleatorios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mostrar_Ordenado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnShell = new javax.swing.JButton();
        btnRadix = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos de Ordenamiento");
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArregloActionPerformed(evt);
            }
        });
        txtArreglo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArregloKeyPressed(evt);
            }
        });
        getContentPane().add(txtArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 61, 30));

        lblArreglo.setText("Tamaño del Arreglo:");
        getContentPane().add(lblArreglo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        numerosAleatorios.setEditable(false);
        numerosAleatorios.setColumns(20);
        numerosAleatorios.setRows(5);
        jScrollPane1.setViewportView(numerosAleatorios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 100));

        mostrar_Ordenado.setEditable(false);
        mostrar_Ordenado.setColumns(20);
        mostrar_Ordenado.setRows(5);
        jScrollPane2.setViewportView(mostrar_Ordenado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 226, 100));

        jButton1.setText("Burbuja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 73, 30));

        jButton2.setText("Quick");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 73, 30));

        jLabel1.setText("Número Aleatorios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabel2.setText("Ordenado con el Método: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        btnShell.setBackground(new java.awt.Color(255, 204, 255));
        btnShell.setText("Shell");
        btnShell.setBorderPainted(false);
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });
        getContentPane().add(btnShell, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 73, 30));

        btnRadix.setBackground(new java.awt.Color(255, 204, 255));
        btnRadix.setText("Radix");
        btnRadix.setBorderPainted(false);
        btnRadix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadixActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadix, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 73, 30));

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, 30));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArregloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArregloActionPerformed

    boolean validarTamañoArreglo() {
        //Si la caja de texto para asignarle valor al arreglo está vacío.
        if (txtArreglo.getText() == "") {
            return false;
        }
        //Validar que lo que se ingresa para su tamño sean números.
        String cadena = txtArreglo.getText();
        if (!cadena.matches("[0-9]+")) {
            return false;
        }
        tamaño = Integer.parseInt(txtArreglo.getText());
        arreglo = new int[tamaño];
        //Alguna otra.
        //
        return true;
    }

    int[] arreglo2;
    
    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        // TODO add your handling code here:

        if (validarTamañoArreglo() == true) {
           
          //mostrar_Ordenado.setText(shell.shell(arreglo2));
          
          if(pulsado()==false)
              return;
           if(pulsado()==true)
              botones=1;
        }
        //vaciarCajaDeTexto();
        lblNombre.setText("Yasmin Ochoa");
    }//GEN-LAST:event_btnShellActionPerformed
    void mostrar(int[] arreglo) {
        String cadena="";
        String cadena2 = "";
        for (int iteracion = 0; iteracion < arreglo.length; iteracion++) {
            arreglo[iteracion] = (int) (Math.random() * 100)+1;
            arreglo2=arreglo;
            cadena += arreglo2[iteracion] + ",";
           // numerosAleatorios.setText(cadena);
            
        }
        
        numerosAleatorios.setText(cadena);
         //arreglo2=arreglo;
    }
    
    int entero;
    int botones;
    public boolean pulsado(){ 
        int personal = entero;
        
        if(personal ==1){
            if(botones==1){
                mostrar_Ordenado.setText(shell.shell(arreglo2));
                personal++;
                return false;
            }
            if(botones==2){
                mostrar_Ordenado.setText(radix.radix(arreglo2));
                personal++;
                
            }
            //personal++;
            return true;
        } 
        
        return false;

        
    }

    public void enterTamañoArreglo_ValoresAleatorios(KeyEvent evt) {
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (validarTamañoArreglo() == true) {
                    mostrar(arreglo);
                    //entero=1;
                }
                
            }
        } catch (NullPointerException error) {
        }

    }
    /*
    void vaciarCajaDeTexto(){
        if(mostrar_Ordenado.getText()!=""){
              txtArreglo.setText("");
        }ñ
    
    }*/
    private void txtArregloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArregloKeyPressed
        // TODO add your handling code here:
        enterTamañoArreglo_ValoresAleatorios(evt);
        entero=1;
    }//GEN-LAST:event_txtArregloKeyPressed

    private void btnRadixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadixActionPerformed
        // TODO add your handling code here:
        if (validarTamañoArreglo() == true) {
           
             //botones=2;
          if(pulsado()==false)
              return;
            //mostrar_Ordenado.setText(radix.radix(arreglo2));
            if(pulsado()==true){
                botones=2;
            }
        }
        //vaciarCajaDeTexto();
        lblNombre.setText("Yasmin Ochoa");
    }//GEN-LAST:event_btnRadixActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        mostrar_Ordenado.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cad2 = q.ordenarQuicksort(arreglo);
        mostrar_Ordenado.setText("ORDENADO POR MÉTODO QUICKSORT:\n"+cad2);
        lblNombre.setText("Miguel Ahumada");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cad2 = b.burbuja(arreglo);
        mostrar_Ordenado.setText("ORDENADO POR MÉTODO BURBUJA:\n"+cad2);
        lblNombre.setText("Miguel Ahumada");
    }//GEN-LAST:event_jButton1ActionPerformed
    private Shell_Sort shell = new Shell_Sort();
    Random numeroAleatorios = new Random();
    int tamaño;
    public int[] arreglo;  //= new int [tamaño];
    private Radix_Sort radix = new Radix_Sort();
    private Burbuja b = new Burbuja();
    private Quicksort q = new Quicksort();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodos_de_Ordenamiento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodos_de_Ordenamiento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodos_de_Ordenamiento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodos_de_Ordenamiento.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodos_de_Ordenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton btnRadix;
    private javax.swing.JButton btnShell;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArreglo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextArea mostrar_Ordenado;
    private javax.swing.JTextArea numerosAleatorios;
    private javax.swing.JTextField txtArreglo;
    // End of variables declaration//GEN-END:variables

}
